### ISSUE TITLE
[beta v1.312] existing gallery alignment lost after installing the beta version ...

### ISSUE THREAD

**Issue by ralfhildebrandt** [fooplugins/foogallery#127]
Hi, after installing the beta today, all existing galleries lost their alignment (usually i had them set to centered). Just thought to notify you ... thx for letting me beta testing.

**Comment by bradvin** [comment]
hi @ralfhildebrandt thanks for reporting this.

It has been fixed in v1.3.13 - please download and test that version. To force the upgrade to happen again on your galleries, please install and activate this cleanup plugin BEFORE you update to the new version : https://github.com/fooplugins/foogallery-beta-cleanup/archive/master.zip
