### ISSUE TITLE
Thumbnails not generated

### ISSUE THREAD

**Issue by tishma** [fooplugins/foogallery#183]
Hi, 
I have a bad case of thumbnails not being generated by FooGallery. My gallery is working fine when I check `Force Original Thumbs`(and no, it's not using the originally uploaded pic as suggested, because WP itself creates the thumbnails in the configured size), but when it's unchecked - gallery page keeps looking for a 'cached' version of thumbnail in:
`media.../cache/2021/07/.../crc32hash.jpg`.
I couldn't find a way to persuade FooGallery to create the thumbnails in this `cache` subdir.

Nothing wrong found here either:
```
<!-- FooGallery Debug Info : Start

ID => 2350
Template => default
Datasource => media_library

FooGallery Settings
===================
default_alignment => fg-center
default_border_size => fg-border-thin
default_drop_shadow => fg-shadow-outline
default_hover_effect_caption_visibility => fg-caption-hover
default_hover_effect_icon => fg-hover-zoom
default_hover_effect_transition => fg-hover-fade
default_hover_effect_type => normal
default_lightbox => none
default_loaded_effect => fg-loaded-fade-in
default_loading_icon => fg-loading-default
default_spacing => fg-gutter-10
default_theme => fg-light
default_thumbnail_dimensions => 
   width => 150
   height => 150
default_thumbnail_link => image
foogallery_items_view => manage

Attachment Info
===============

FooGallery Debug Info : End -->
```
I'm okay with using the "original thumbs" (although it took me hours to figure out this option), but I believe you guys have a problem here.

Cheers
Vladimir

**Comment by bradvin** [comment]
hi @tishma,

In your case, enabling `Force Original Thumbs` will work for you because your thumb size is 150x150 and that is the default thumbnail size in WP by default. If you change the thumb dimensions in FooGallery then it will start using the Full Size images, which is not ideal.

With `Force Original Thumbs` disabled, FooGallery will automatically try to generate thumbs and store them in the cache folder. If you check your HTML and the thumbnail image src is pointing to the cache folder location, then that means they are being generated behind the scenes, but are just not accessible and it could be a permissions problem on your web server. 

If the HTML is NOT pointing to images within the cache folder, then the thumbs are likely not being generated to begin with. There could be a number of reasons for this, but is hard to tell without you sharing your system info (from FooGallery -> System Info). You can also do a thumb generation test from the Settings page to get the error response.

**Comment by tishma** [comment]
Thanks @bradvin,

Again, HTML is pointing to cache folder when I leave Force Original unchecked, but the thumbs are not generated.

I figured that could be about permissions, and if it is - it's because the hosting provider had changed something that I really don't have time to investigate (I have a bunch of old thumbnails behaving).

If it is the properties - it'd be great if `Run Tests` actually failed with the appropriate feedback (instead of showing success). And `View Thumb Test Page` which btw shows cache URLs, but can't display the thumbs as they have not been generated - could also indicate the permissions problem.

Cheers
v.
